(package "alt-codes"
         "0.0.5"
         "Insert alt codes using meta key")

(website-url "https://github.com/jcs-elpa/alt-codes")
(keywords "convenience" "alt" "codes" "insertion" "meta")

(package-file "alt-codes.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
